Shop/Shop/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import ListView, DetailView
from django.contrib.auth.decorators import login_required
from Shop import settings

from shop_app.models import Product, Profile, Category
from shop_app.views import ProductDetailView, SearchProductListView, CategoryProductListView, ProductListView, \
    ProfileView, CategoryListView

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Shop.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^sign_up/$', 'shop_app.views.sign_up', name='sign_up'),
    url(r'^sign_in/$', 'shop_app.views.sign_in', name='sign_in'),
    url(r'^sign_out/$', 'shop_app.views.sign_out', name='sign_out'),
    url(r'^set_lang/$', 'shop_app.views.set_language', name='set_lang'),

    url(
        r'^profile/(?P<pk>\d+)$',
        login_required(ProfileView.as_view())
    ),
    url(r'^profile/$', 'shop_app.views.profile', name='profile'),
    url(r'^profile/edit/$', 'shop_app.views.edit_profile', name='edit_profile'),
    url(r'^profile/avatar/(?P<prof>\d+)$', 'shop_app.views.avatar_download', name='avatar_download'),


    url(
        r'^$',
        login_required(ProductListView.as_view()),
        name='index'
    ),

    url(
        r'^search/$',
        login_required(SearchProductListView.as_view()),
        name='search'
    ),

    url(
        r'^product/(?P<pk>\d+)$',
        login_required(ProductDetailView.as_view()),
        name='product'
    ),

    url(
        r'^cart/$',
        'shop_app.views.cart',
        name='cart'
    ),

    url(
        r'^cart/add/$',
        'shop_app.views.add_to_cart',
        name='add_to_cart'
    ),

    url(
        r'^cart/del/$',
        'shop_app.views.del_from_cart',
        name='del_from_cart'
    ),

    url(
        r'^orders/$',
        'shop_app.views.my_orders',
        name='my_orders'
    ),

    url(
        r'^categories/$',
        login_required(CategoryListView.as_view()),
        name='categories'
    ),

    url(
        r'^category/(?P<cat>\d+)$',
        login_required(CategoryProductListView.as_view()),
        name='category_prods'
    ),
    
    url(r'^manage/', include('manager_app.urls', namespace='manage')),

)

urlpatterns += patterns('',
    url(
        r'^media/(?P<path>.*)',
        'django.views.static.serve',
        { 'document_root': settings.MEDIA_ROOT }
    )
)

Shop/manager_app/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import ListView, DetailView
from django.contrib.auth.decorators import login_required

from rel_app.models import Order
from shop_app.models import Category


urlpatterns = patterns('',
    url(r'^$',
        login_required(ListView.as_view(
            model=Order,
            paginate_by=5,
            template_name="manager_app/all_orders.html"
        )),
        name="index"),
    url(r'new_product/', 'manager_app.views.new_product', name='new_product'),
    url(r'save_char/', 'manager_app.views.save_char', name='save_char'),
    url(
        r'all_orders/',
        login_required(ListView.as_view(
            model=Order,
            paginate_by=5,
            template_name="manager_app/all_orders.html"
        )),
        name='all_orders'
    ),

    url(r'^new_category/$', 'manager_app.views.new_category', name='new_category'),
        url(
        r'^categories/$',
        login_required(ListView.as_view(
            model=Category,
            template_name="manager_app/categories.html",
            queryset=Category.objects.filter(parent__isnull=True)
        )),
        name='categories'
    ),

)

Shop/manager_app/models.py
from django.db import models
from django.contrib.auth.models import User
from rel_app.models import Address
from shop_app.models import Product


class Manufacturer(models.Model):
    name = models.CharField(max_length=256)
    owner = models.CharField(max_length=256)
    address = models.ForeignKey(Address)
    contact = models.CharField(max_length=1024)
    email = models.EmailField(max_length=254, null=True, blank=True)
    web_site = models.URLField(max_length=254, null=True, blank=True)

    def __unicode__(self):
        return self.name


class Consignment(models.Model):
    product = models.ForeignKey(Product)
    init_quantity = models.PositiveIntegerField()
    quantity_left = models.PositiveIntegerField()

    def __unicode__(self):
        return u'%s: %s' % (self.product.name, self.init_quantity)


class Store(models.Model):
    consignment = models.ForeignKey(Consignment)
    cost = models.PositiveIntegerField()
    manufacturer = models.ForeignKey(Manufacturer)
    receive_date = models.DateField(auto_now_add=True)
    receive_person = models.ForeignKey(User)

    def __unicode__(self):
        return u'%s: %s | %s' % (self.consignment.name, self.manufacturer, self.receive_date)

Shop/rel_app/models.py
from django.db import models
from django.contrib.auth.models import User

STATUS = (
    ('U', 'Unpaid'),
    ('P', 'Paid'),
    ('C', 'Cancelled'),
    ('D', 'Delivered')
)


class Address(models.Model):
    country = models.CharField(max_length=256)
    region = models.CharField(max_length=256)
    city = models.CharField(max_length=256)
    addr = models.CharField(max_length=256)
    postcode = models.PositiveIntegerField()

    def __unicode__(self):
        return u'%s, %s, %s, %s' % (self.country, self.region, self.city, self.addr)

    class Meta:
        verbose_name_plural = "addresses"


class DeliveryAddress(Address):
    profile = models.ForeignKey("shop_app.Profile", related_name="addresses")

    def __unicode__(self):
        return u'%s: %s, %s, %s, %s' % (self.profile, self.country, self.region, self.city, self.addr)

    class Meta:
        verbose_name_plural = "delivery addresses"


class Order(models.Model):
    user = models.ForeignKey(User)
    product = models.ForeignKey("shop_app.Product")
    count = models.PositiveIntegerField(default=1)
    status = models.CharField(max_length=1, choices=STATUS, default='U')
    dateTime = models.DateTimeField(auto_now_add=True)
    address = models.ForeignKey(DeliveryAddress)

    def __unicode__(self):
        return u'%s: %s | %s' % (self.user, self.product, self.dateTime)

PAYMENT_METHOD = (
    ('A', 'Card'),
    ('B', 'Cash'),
    ('C', 'Coupon')
)


class Payment(models.Model):
    order = models.OneToOneField(Order, primary_key=True)
    amount = models.PositiveIntegerField()
    transaction_id = models.CharField(max_length=256, null=True, blank=True)
    payment_method = models.CharField(max_length=1, choices=PAYMENT_METHOD)
    dateTime = models.DateTimeField(auto_now_add=True)

Shop/shop_app/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=256)
    parent = models.ForeignKey('self', null=True, blank=True, related_name='children')

    def get_all_children(self):
        r = [self]
        for c in Category.objects.filter(parent=self):
            r.append(c.get_all_children())
        return r

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = "categories"


CHARACTERISTIC_TYPE = (
    ('B', 'Boolean'),
    ('P', 'Positive Number'),
    ('C', 'Choose')
)


class Characteristic(models.Model):
    name = models.CharField(max_length=256)
    type_of_char = models.CharField(blank=True, max_length=1, choices=CHARACTERISTIC_TYPE, default='C')

    def __unicode__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=256)
    price = models.PositiveIntegerField()
    description = models.TextField(blank=True)
    image = models.ImageField(null=True, blank=True)
    category = models.ForeignKey(Category)

    def __unicode__(self):
        return self.name


class ProductCharacteristic(models.Model):
    product = models.ForeignKey(Product, related_name='characteristics')
    characteristic = models.ForeignKey(Characteristic)
    value = models.CharField(max_length=256, blank=True)

    def __unicode__(self):
        return u'%s - %s' % (self.product, self.characteristic)


class Comment(models.Model):
    author = models.ForeignKey(User)
    product = models.ForeignKey(Product)
    content = models.TextField(max_length=4096)
    dateTime = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return u'%s - %s | %s' % (self.author, self.product, self.dateTime)


class Message(models.Model):
    author = models.ForeignKey(User, related_name='msg_author')
    recipient = models.ForeignKey(User, related_name='msg_recipient')
    content = models.TextField()
    dateTime = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return u'%s - %s | %s' % (self.author, self.recipient, self.dateTime)

GENDER = (
    ('M', 'Male'),
    ('F', 'Female')
)


class Profile(models.Model):
    user = models.OneToOneField(User, related_name='profile')
    full_name = models.CharField(blank=True, max_length=256)
    gender = models.CharField(blank=True, max_length=1, choices=GENDER)
    avatar = models.ImageField(blank=True, upload_to='avatars')
    email = models.EmailField(blank=True, max_length=254)
    birthday = models.DateField(blank=True, null=True)
    about = models.TextField(blank=True)

    def __unicode__(self):
        return u'%s: %s' % (self.user, self.full_name)

Shop/manager_app/forms.py
from django import forms
from shop_app.models import Category, Characteristic


class CategoryCreateForm(forms.ModelForm):
    parent = forms.ModelChoiceField(queryset=Category.objects.all(), required=False)

    class Meta:
        model = Category


class CharacteristicForm(forms.ModelForm):
    class Meta:
        model = Characteristic

Shop/manager_app/views.py
import json
from django.core import serializers
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.utils.safestring import SafeString
from django.forms.models import model_to_dict

from shop_app.models import Product, Characteristic, ProductCharacteristic
from manager_app.forms import *


@login_required
def new_product(request):
    if request.POST:
        p = Product()
        p.name = request.POST["name"]
        p.category = Category.objects.get(id=request.POST["category"])
        p.price = request.POST["price"]
        p.description = request.POST["description"]
        if "image" in request.POST:
            p.image = request.POST["image"]
        p.save()
        for ch in request.POST:
            if ch.startswith('ch_value_'):
                ch_id = int(ch.replace('ch_value_', ''))
                char = Characteristic.objects.get(id=ch_id)
                prod_char = ProductCharacteristic(product=p, characteristic=char, value=request.POST[ch])
                prod_char.save()
        return HttpResponseRedirect(reverse('manage:new_product'))
    else:
        form = CharacteristicForm()
        return render(
            request,
            "manager_app/new_product.html",
            {
                "categories": Category.objects.all(),
                "characteristics": SafeString(serializers.serialize("json", Characteristic.objects.all())),
                "form": form
            }
        )


@login_required()
def new_category(request):
    c = Category()
    if request.method == 'POST':
        form = CategoryCreateForm(request.POST, instance=c)
    else:
        form = CategoryCreateForm(instance=c)

    if form.is_valid():
        c.save()
        form.save()
        return HttpResponseRedirect(reverse('manage:categories'))
    return render(
        request,
        "manager_app/new_category.html",
        {
            "form": form,
        }
    )


@login_required()
def save_char(request):
    ch = Characteristic()
    if request.POST:
        ch.name = request.POST["name"]
        ch.type_of_char = request.POST["type_of_char"]
        ch.save()
    return HttpResponse(json.dumps(model_to_dict(ch)), content_type="application/json")

Shop/templates/manager_app/all_orders.html
{% extends "manager_app/base.html" %}
{% load tags %}

{% block head_title %}- orders{% endblock %}

{% block title %}
    Orders
{% endblock %}

{% block content %}
    {% if order_list %}
        {% for order in order_list %}
            <div class="list_item">
                {{ order.user.name }}
                <img src="{{ order.product.image.url }}"/>
                {{ order.product.name }} {{ order.product.price }}
                {{ order.count }}
                {{ order.status }}
                {{ order.dateTime }}
            </div>
        {% endfor %}
        {% if is_paginated %}
            <div class="pagination">
                <span class="page-links">
                    {% if page_obj.has_previous %}
                        <a href="?{% url_replace request 'page' page_obj.previous_page_number %}">previous</a>
                    {% endif %}
                    <span class="page-current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>
                    {% if page_obj.has_next %}
                        <a href="?{% url_replace request 'page' page_obj.next_page_number %}">next</a>
                    {% endif %}
                </span>
            </div>
        {% endif %}
    {% else %}
        <p>There is no orders</p>
    {% endif %}
{% endblock %}

Shop/templates/manager_app/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Shop {% block head_title %}{% endblock %}</title>
    <link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
    <script language="javascript" type="text/javascript" src="{% static 'js/jquery-2.1.1.js' %}"></script>
    <script language="javascript" type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>

    <link type="text/css" rel="stylesheet" href="{% static 'js/jquery-ui-1.11.2.custom/jquery-ui.css' %}" />
    <script src="{% static 'js/jquery-ui-1.11.2.custom/jquery-ui.js' %}"></script>
</head>
<body>
    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'index' %}">Shop</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'index' %}">Home<span class="sr-only">(current)</span></a></li>
          </ul>
          <form class="navbar-form navbar-left" role="search" action="{% url 'search' %}" method="get">
              {% comment %}{% csrf_token %}{% endcomment %}
              <div class="form-group">
                  <input type="text" class="form-control" placeholder="Search" name="q">
              </div>
              <button type="submit" class="btn btn-default">Submit</button>
          </form>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'sign_out' %}">Log out</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Lang<span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">English</a></li>
                <li><a href="#">Russian</a></li>
                <li class="divider"></li>
                <li><a href="#">Default (English)</a></li>
              </ul>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <ul class="nav nav-pills">
        <li><a href="{% url 'manage:all_orders' %}">Orders</a></li>
        <li><a href="{% url 'index' %}">Products</a></li>
        <li><a href="{% url 'manage:categories' %}">Categories</a></li>
        <li><a href="{% url 'manage:new_product' %}">New product</a></li>
        <li><a href="#">Contact</a></li>
    </ul>
    <div class="jumbotron">
        <h1>
            {% block title %}
            {% endblock %}
        </h1>
        <h2>
            {% block sub_title %}
            {% endblock %}
        </h2>
    </div>
    <div class="content">
        {% block content %}
        {% endblock %}
    </div>
    <div class="footer" id="footer">
        2014
    </div>
</body>
</html>

Shop/templates/manager_app/categories.html
{% extends "manager_app/base.html" %}
{% load tags %}

{% block head_title %}- categories{% endblock %}

{% block title %}
    Categories
{% endblock %}

{% block content %}
    <a calss="btn" href="{% url "manage:new_category" %}">New category</a>
    <ul>
    {% for c in category_list %}
        <li><a href="{% url 'category_prods' c.id %}">{{ c.name }}</a>
        {% children_tag c %}
        </li>
    {% endfor %}
    </ul>
{% endblock %}

Shop/templates/manager_app/new_category.html
{% extends "manager_app/base.html" %}
{% load static %}

{% block head_title %}- new category{% endblock %}

{% block title %}
    Create category
{% endblock %}

{% block content %}
    <form action="{% url 'manage:new_category' %}" method="POST" enctype="multipart/form-data" >
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create" />
    </form>
{% endblock %}

Shop/templates/manager_app/new_product.html
{% extends "manager_app/base.html" %}

{% block head_title %}- new product{% endblock %}

{% block title %}
    Create product
{% endblock %}

{% block content %}
    <form action="{% url 'manage:new_product' %}" method="POST">
        {% csrf_token %}
        <p>Name: <input type="text" name="name"/></p>
        <p>Category:
            <select name="category">
                {% for cat in categories %}
                    <option value="{{ cat.id }}">{{ cat.name }}</option>
                {% endfor %}
            </select>
        </p>
        <p>Price: <input type="text" name="price"/></p>
        <p>Description:</p>
        <textarea name="description"></textarea>
        <p>Image: <input type="file" name="image"/></p>
        <p><input type="submit" value="Create"/></p>
        <p>
            Characteristics:
            <div id="chars" name="prod_characteristics">

            </div>
            <div id="dialog" title="Success" style="display:none">
                <p>New characteristic was created.</p>
            </div>
        </p>
    </form>
    <button id="add_char_button">Add characteristic</button>
    <p>
        {{ form.as_p }}
        <button id="new_char_button">New characteristic</button>
    </p>

    <script type="text/javascript">
        var characteristics = {{ characteristics }};
        function generateSelect() {
            var select_temp = document.createElement("select");
            var default_blank = document.createElement("option");
            default_blank.appendChild(document.createTextNode(" -- select an option -- "));
            default_blank.setAttribute("disabled","");
            default_blank.setAttribute("selected","");
            select_temp.appendChild(default_blank);
            for (var i in characteristics) {
                var node = document.createElement("option");
                node.appendChild(document.createTextNode(characteristics[i].fields.name));
                node.setAttribute("value", characteristics[i].pk);
                select_temp.appendChild(node);
            }
            return select_temp;
        }

        var add_button = document.getElementById("add_char_button");
        var chars = document.getElementById("chars");
        var char_index = 0;
        add_button.onclick = function() {
            var char_select_list = generateSelect();
            char_select_list.setAttribute("id", "ch_"+(char_index ++));
            var paragraph = document.createElement("p");
            paragraph.appendChild(char_select_list);
            chars.appendChild(paragraph);
            char_select_list.onchange = function() {
                if (paragraph.childElementCount > 1) {
                    paragraph.removeChild(paragraph.lastChild);
                }
                var selected_char_id = char_select_list.options[char_select_list.selectedIndex].value;
                var selected_char;
                for (var i in characteristics) {
                    if (selected_char_id == characteristics[i].pk) {
                        selected_char = characteristics[i];
                        break;
                    }
                }
                var input;
                switch (selected_char.fields.type_of_char) {
                    case 'B':
                        input = document.createElement("input");
                        input.setAttribute("id", "ch_value_"+selected_char_id);
                        input.setAttribute("name", "ch_value_"+selected_char_id);
                        input.setAttribute("type", "checkbox");
                        var hidden_default = document.createElement("input");
                        hidden_default.setAttribute("id", "ch_value_"+selected_char_id);
                        hidden_default.setAttribute("name", "ch_value_"+selected_char_id);
                        hidden_default.setAttribute("type", "hidden");
                        hidden_default.setAttribute("value", "false");
                        paragraph.appendChild(hidden_default);
                        break;
                    case 'P':
                        input = document.createElement("input");
                        input.setAttribute("id", "ch_value_"+selected_char_id);
                        input.setAttribute("name", "ch_value_"+selected_char_id);
                        input.setAttribute("type", "text");
                        break;
                    case 'C':
                        //TODO change to select from list
                        input = document.createElement("input");
                        input.setAttribute("id", "ch_value_"+selected_char_id);
                        input.setAttribute("name", "ch_value_"+selected_char_id);
                        input.setAttribute("type", "text");
                        break;
                }
                paragraph.appendChild(input);
            };
        };

        var new_button = document.getElementById("new_char_button");
        new_button.onclick = function() {
            if (document.getElementById("id_name").value) {
                jQuery.ajax({
                    url: '{% url 'manage:save_char' %}',
                    type: 'POST',
                    data: {
                        "name": document.getElementById("id_name").value,
                        "type_of_char": document.getElementById("id_type_of_char").value,
                        "csrfmiddlewaretoken": getCookie("csrftoken")
                    },
                    success: function(response) {
                        for (var i = 0; i < char_index; i++) {
                            var node = document.getElementById("ch_"+i);
                            var ch = document.createElement("option");
                            ch.appendChild(document.createTextNode(response.name));
                            ch.setAttribute("value", response.id);
                            node.appendChild(ch);
                        }
                        characteristics.push({
                            "pk": response.id,
                            "fields": {
                                "name": response.name,
                                "type_of_char": response.type_of_char
                            },
                            "model": "shop_app.characteristic"
                        });
                        document.getElementById("id_name").value = "";
                        $(function() {
                            $( "#dialog" ).dialog();
                        });
                    }
                });
            }
        };
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie != '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) == (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

    </script>
{% endblock %}