Shop/Shop/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import ListView, DetailView
from django.contrib.auth.decorators import login_required
from Shop import settings

from shop_app.models import Product, Profile, Category
from shop_app.views import ProductDetailView, SearchProductListView, CategoryProductListView, ProductListView, \
    ProfileView, CategoryListView

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Shop.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^sign_up/$', 'shop_app.views.sign_up', name='sign_up'),
    url(r'^sign_in/$', 'shop_app.views.sign_in', name='sign_in'),
    url(r'^sign_out/$', 'shop_app.views.sign_out', name='sign_out'),
    url(r'^set_lang/$', 'shop_app.views.set_language', name='set_lang'),

    url(
        r'^profile/(?P<pk>\d+)$',
        login_required(ProfileView.as_view())
    ),
    url(r'^profile/$', 'shop_app.views.profile', name='profile'),
    url(r'^profile/edit/$', 'shop_app.views.edit_profile', name='edit_profile'),
    url(r'^profile/avatar/(?P<prof>\d+)$', 'shop_app.views.avatar_download', name='avatar_download'),


    url(
        r'^$',
        login_required(ProductListView.as_view()),
        name='index'
    ),

    url(
        r'^search/$',
        login_required(SearchProductListView.as_view()),
        name='search'
    ),

    url(
        r'^product/(?P<pk>\d+)$',
        login_required(ProductDetailView.as_view()),
        name='product'
    ),

    url(
        r'^cart/$',
        'shop_app.views.cart',
        name='cart'
    ),

    url(
        r'^cart/add/$',
        'shop_app.views.add_to_cart',
        name='add_to_cart'
    ),

    url(
        r'^cart/del/$',
        'shop_app.views.del_from_cart',
        name='del_from_cart'
    ),

    url(
        r'^orders/$',
        'shop_app.views.my_orders',
        name='my_orders'
    ),

    url(
        r'^categories/$',
        login_required(CategoryListView.as_view()),
        name='categories'
    ),

    url(
        r'^category/(?P<cat>\d+)$',
        login_required(CategoryProductListView.as_view()),
        name='category_prods'
    ),
    
    url(r'^manage/', include('manager_app.urls', namespace='manage')),

)

urlpatterns += patterns('',
    url(
        r'^media/(?P<path>.*)',
        'django.views.static.serve',
        { 'document_root': settings.MEDIA_ROOT }
    )
)

Shop/rel_app/models.py
from django.db import models
from django.contrib.auth.models import User

STATUS = (
    ('U', 'Unpaid'),
    ('P', 'Paid'),
    ('C', 'Cancelled'),
    ('D', 'Delivered')
)


class Address(models.Model):
    country = models.CharField(max_length=256)
    region = models.CharField(max_length=256)
    city = models.CharField(max_length=256)
    addr = models.CharField(max_length=256)
    postcode = models.PositiveIntegerField()

    def __unicode__(self):
        return u'%s, %s, %s, %s' % (self.country, self.region, self.city, self.addr)

    class Meta:
        verbose_name_plural = "addresses"


class DeliveryAddress(Address):
    profile = models.ForeignKey("shop_app.Profile", related_name="addresses")

    def __unicode__(self):
        return u'%s: %s, %s, %s, %s' % (self.profile, self.country, self.region, self.city, self.addr)

    class Meta:
        verbose_name_plural = "delivery addresses"


class Order(models.Model):
    user = models.ForeignKey(User)
    product = models.ForeignKey("shop_app.Product")
    count = models.PositiveIntegerField(default=1)
    status = models.CharField(max_length=1, choices=STATUS, default='U')
    dateTime = models.DateTimeField(auto_now_add=True)
    address = models.ForeignKey(DeliveryAddress)

    def __unicode__(self):
        return u'%s: %s | %s' % (self.user, self.product, self.dateTime)

PAYMENT_METHOD = (
    ('A', 'Card'),
    ('B', 'Cash'),
    ('C', 'Coupon')
)


class Payment(models.Model):
    order = models.OneToOneField(Order, primary_key=True)
    amount = models.PositiveIntegerField()
    transaction_id = models.CharField(max_length=256, null=True, blank=True)
    payment_method = models.CharField(max_length=1, choices=PAYMENT_METHOD)
    dateTime = models.DateTimeField(auto_now_add=True)

Shop/shop_app/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=256)
    parent = models.ForeignKey('self', null=True, blank=True, related_name='children')

    def get_all_children(self):
        r = [self]
        for c in Category.objects.filter(parent=self):
            r.append(c.get_all_children())
        return r

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = "categories"


CHARACTERISTIC_TYPE = (
    ('B', 'Boolean'),
    ('P', 'Positive Number'),
    ('C', 'Choose')
)


class Characteristic(models.Model):
    name = models.CharField(max_length=256)
    type_of_char = models.CharField(blank=True, max_length=1, choices=CHARACTERISTIC_TYPE, default='C')

    def __unicode__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=256)
    price = models.PositiveIntegerField()
    description = models.TextField(blank=True)
    image = models.ImageField(null=True, blank=True)
    category = models.ForeignKey(Category)

    def __unicode__(self):
        return self.name


class ProductCharacteristic(models.Model):
    product = models.ForeignKey(Product, related_name='characteristics')
    characteristic = models.ForeignKey(Characteristic)
    value = models.CharField(max_length=256, blank=True)

    def __unicode__(self):
        return u'%s - %s' % (self.product, self.characteristic)


class Comment(models.Model):
    author = models.ForeignKey(User)
    product = models.ForeignKey(Product)
    content = models.TextField(max_length=4096)
    dateTime = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return u'%s - %s | %s' % (self.author, self.product, self.dateTime)


class Message(models.Model):
    author = models.ForeignKey(User, related_name='msg_author')
    recipient = models.ForeignKey(User, related_name='msg_recipient')
    content = models.TextField()
    dateTime = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return u'%s - %s | %s' % (self.author, self.recipient, self.dateTime)

GENDER = (
    ('M', 'Male'),
    ('F', 'Female')
)


class Profile(models.Model):
    user = models.OneToOneField(User, related_name='profile')
    full_name = models.CharField(blank=True, max_length=256)
    gender = models.CharField(blank=True, max_length=1, choices=GENDER)
    avatar = models.ImageField(blank=True, upload_to='avatars')
    email = models.EmailField(blank=True, max_length=254)
    birthday = models.DateField(blank=True, null=True)
    about = models.TextField(blank=True)

    def __unicode__(self):
        return u'%s: %s' % (self.user, self.full_name)

Shop/shop_app/forms.py
from django import forms
from django.forms import RadioSelect
from shop_app.models import Profile
from shop_app import models


class LoginForm(forms.Form):
    username = forms.CharField(max_length=30)
    password = forms.CharField(widget=forms.PasswordInput, max_length=30)


class SignUpForm(forms.Form):
    username = forms.CharField(max_length=30)
    password = forms.CharField(widget=forms.PasswordInput, max_length=30)
    confirm = forms.CharField(widget=forms.PasswordInput, max_length=30)


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['full_name', 'gender', 'avatar', 'email', 'birthday', 'about']
        widgets = {
            'gender': RadioSelect(dict(models.GENDER)),
        }

Shop/shop_app/views.py
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse_lazy, reverse
from django.db.models import Q, F
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.utils.translation import check_for_language
from django.views.generic import DetailView, ListView
import operator
from Shop import settings
from rel_app.models import Order

from shop_app.forms import LoginForm, ProfileEditForm, SignUpForm
from shop_app.models import Product, Profile, Category


def lang(template_name):
    def decor(view):
        def wrapper(request):
            templ = template_name
            if settings.LANGUAGE_COOKIE_NAME in request.COOKIES and request.COOKIES[settings.LANGUAGE_COOKIE_NAME] == 'ru':
                idx = templ.index('/')
                templ = templ[:idx] + '/ru' + templ[idx:]
            response = view(request, template_name=templ)
            return response
        return wrapper
    return decor


def lang_for_class_view(template_getter, view):
    template_names = template_getter
    if settings.LANGUAGE_COOKIE_NAME in view.request.COOKIES and view.request.COOKIES[settings.LANGUAGE_COOKIE_NAME] == 'ru':
        templ = template_names[0]
        idx = templ.index('/')
        templ = templ[:idx] + '/ru' + templ[idx:]
        template_names[0] = templ
    return template_names


def no_auth_please(v):
    def wrapper(request, template_name, *a, **k):
        user = request.user
        if user.is_authenticated():
            return HttpResponseRedirect(reverse("index"))
        else:
            return v(request, template_name, *a, **k)
    return wrapper


@lang(template_name="shop_app/my_orders.html")
@login_required
def my_orders(request, template_name):
    user_id = request.user.id
    ord_list = Order.objects.raw('SELECT * from rel_app_order WHERE user_id = %s', [user_id])
    return render(
        request,
        template_name,
        {
            "order_list": ord_list
        }
    )


@lang(template_name='shop_app/sign_in.html')
@no_auth_please
def sign_in(request, template_name):
    if request.POST:
        f = LoginForm(request.POST)
        if f.is_valid():
            user = authenticate(
                username=f.cleaned_data["username"],
                password=f.cleaned_data["password"]
            )
            if user:
                login(request, user)
                response = None
                if "next" in request.GET:
                    response = HttpResponseRedirect(request.GET["next"])
                else:
                    response = HttpResponseRedirect(reverse('index'))
                if "language" not in request.COOKIES:
                    response.set_cookie(settings.LANGUAGE_COOKIE_NAME, "", max_age=30*24*60*60)
                return response

            else:
                return HttpResponseRedirect(reverse('sign_in'))
        else:
            return HttpResponseRedirect(reverse('sign_in'))
    else:
        f = LoginForm()
        context = {"f": f}
        if 'next' in request.GET:
            context["next"] = request.GET["next"]
        return render(request, template_name, context)


@lang(template_name='shop_app/sign_up.html')
@no_auth_please
def sign_up(request, template_name):
    f = SignUpForm(request.POST or None)
    if request.POST:
        if f.is_valid():
            us = f.cleaned_data["username"]
            pas = f.cleaned_data["password"]
            conf = f.cleaned_data["confirm"]
            if pas == conf:
                us = User.objects.create_user(username=us, password=pas)
                p = Profile(user=us)
                p.save()
                return HttpResponseRedirect(reverse('edit_profile'))
            return HttpResponseRedirect(reverse('sign_up'))
        else:
            return HttpResponseRedirect(reverse('sign_up'))
    else:
        return render(request, template_name, {"form": f})


@login_required()
def sign_out(request):
    logout(request)
    return HttpResponseRedirect(reverse('sign_in'))


@login_required()
def profile(request):
    p = None
    try:
        p = request.user.profile
    except Profile.DoesNotExist:
        pass
    if not p:
        p = Profile(user=request.user)
        p.save()
    return HttpResponseRedirect(p.id)


class ProfileView(DetailView):
    model = Profile
    template_name = "shop_app/profile.html"

    def get_template_names(self):
        return lang_for_class_view(super(ProfileView, self).get_template_names(), self)


@lang(template_name="shop_app/edit_profile.html")
@login_required()
def edit_profile(request, template_name):
    p = request.user.profile
    if request.method == 'POST':
        if not p:
            p = Profile(user=request.user)
        form = ProfileEditForm(request.POST, request.FILES, instance=p)
        if form.is_valid():
            p.save()
            form.save()
        return HttpResponseRedirect(reverse('profile'))
    else:
        if not p:
            p = Profile(user=request.user)
            p.save()
        form = ProfileEditForm(instance=p)
        return render(
            request,
            template_name,
            {
                "form": form,
                'image': p.avatar
            }
        )


@login_required()
def avatar_download(request, prof):
    user_profile = Profile.objects.get(id=prof)
    filename = user_profile.avatar.name.split('/')[-1]
    response = HttpResponse(user_profile.avatar, content_type='image')
    response['Content-Disposition'] = 'attachment; filename=%s' % filename
    return response


class ProductDetailView(DetailView):
    model = Product
    template_name = "shop_app/product.html"

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        chain = []
        category = self.get_object().category
        while category.parent:
            chain.insert(0, category)
            category = category.parent
        chain.insert(0, category)
        context['category_chain'] = chain
        return context

    def get_template_names(self):
        return lang_for_class_view(super(ProductDetailView, self).get_template_names(), self)


class ProductListView(ListView):
    model = Product
    paginate_by = 5
    template_name = 'shop_app/product_list.html'

    def get_template_names(self):
        return lang_for_class_view(super(ProductListView, self).get_template_names(), self)


class SearchProductListView(ListView):
    model = Product
    paginate_by = 5
    template_name = "shop_app/product_list.html"

    def get_queryset(self):
        get_dict = self.request.GET
        filter_list = []
        if 'q' in get_dict:
            filter_list.append(Q(name__contains=get_dict['q']))
        if 'max' in get_dict and 'min' in get_dict:
            filter_list.append(Q(price__gt=get_dict['min']))
            filter_list.append(Q(price__lt=get_dict['max']))
        qs = None
        if 'category' in get_dict:
            cat_view = CategoryProductListView(kwargs={'cat':get_dict['category']})
            qs = cat_view.get_queryset()
        if qs:
            qs = qs.filter(reduce(operator.and_, filter_list, Q(name__contains='')))
        else:
            qs = Product.objects.filter(reduce(operator.and_, filter_list, Q(name__contains='')))
        return qs

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(SearchProductListView, self).get_context_data(**kwargs)
        context['query'] = self.request.GET.get('q', '')
        return context

    def get_template_names(self):
        return lang_for_class_view(super(SearchProductListView, self).get_template_names(), self)


class CategoryListView(ListView):
    model = Category
    template_name = "shop_app/categories.html"
    queryset = Category.objects.filter(parent__isnull=True)

    def get_template_names(self):
        return lang_for_class_view(super(CategoryListView, self).get_template_names(), self)


class CategoryProductListView(ListView):
    model = Product
    paginate_by = 5
    template_name = "shop_app/product_list.html"

    def get_queryset(self):
        parent_category = Category.objects.get(id=self.kwargs['cat'])
        categories = []
        self.__category_list(parent=parent_category, cat_list=categories)
        qs = Product.objects.filter(category__in=categories).filter(name=F('name'))
        return qs

    def __category_list(self, parent, cat_list):
        cat_list.append(parent)
        if parent.children.count > 0:
            for c in parent.children.all():
                self.__category_list(c, cat_list)

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(CategoryProductListView, self).get_context_data(**kwargs)
        context['category'] = Category.objects.get(id=self.kwargs['cat'])
        return context

    def get_template_names(self):
        return lang_for_class_view(super(CategoryProductListView, self).get_template_names(), self)


@lang(template_name="shop_app/cart.html")
@login_required()
def cart(request, template_name):
    if "cart" not in request.session:
        request.session["cart"] = {}
    sh_cart = request.session["cart"]
    items = [
        {
            "product": Product.objects.get(id=item),
            "count": sh_cart[item],
            "sum": Product.objects.get(id=item).price*int(sh_cart[item])
        } for item in sh_cart.keys()]
    cart_sum = sum(item['sum'] for item in items)
    return render(
        request,
        template_name,
        {
            'items': items,
            'sum': cart_sum
        }
    )


@login_required()
def add_to_cart(request):
    product = Product.objects.get(id=request.POST["product"])

Shop/templates/shop_app/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Shop {% block head_title %}{% endblock %}</title>
    <link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
    <script language="javascript" type="text/javascript" src="{% static 'js/jquery-2.1.1.js' %}"></script>
    <script language="javascript" type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>

    <link type="text/css" rel="stylesheet" href="{% static 'js/jquery-ui-1.11.2.custom/jquery-ui.css' %}" />
    <script src="{% static 'js/jquery-ui-1.11.2.custom/jquery-ui.js' %}"></script>
</head>
<body>
    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'index' %}">Shop</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'index' %}">Home<span class="sr-only">(current)</span></a></li>
          </ul>
          <form class="navbar-form navbar-left" role="search" action="{% url 'search' %}" method="get">
              {% comment %}{% csrf_token %}{% endcomment %}
              <div class="form-group">
                  <input type="text" class="form-control" placeholder="Search" name="q">
              </div>
              <button type="submit" class="btn btn-default">Submit</button>
          </form>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'sign_out' %}">Log out</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Lang<span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="{% url 'set_lang' %}?language=en">English</a></li>
                <li><a href="{% url 'set_lang' %}?language=ru">Russian</a></li>
                <li class="divider"></li>
                <li><a href="#">Default (English)</a></li>
              </ul>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <ul class="nav nav-pills">
        <li><a href="{% url 'profile' %}">Profile</a></li>
        <li><a href="{% url 'cart' %}">Shopping cart</a></li>
        <li><a href="{% url 'categories' %}">Categories</a></li>
        <li><a href="{% url 'my_orders' %}">My orders</a></li>
        <li><a href="#">My messages</a></li>
        <li class="navbar-right"><a href="{% url 'manage:index' %}">Manage</a></li>
    </ul>
    <div class="jumbotron">
        <h1>
            {% block title %}
            {% endblock %}
        </h1>
        <h2>
            {% block sub_title %}
            {% endblock %}
        </h2>
    </div>
    <div class="content">
        {% block content %}
        {% endblock %}
    </div>
    <div name="buffer" style="margin-top:75px">
    </div>
    <div id="footer" class="container">
    <nav class="navbar navbar-default navbar-fixed-bottom">
        <div class="navbar-inner navbar-content-center">
            <p class="text-muted credit">
                2014
            </p>
        </div>
    </nav>
</div>
</body>
</html>

Shop/templates/shop_app/cart.html
{% extends "shop_app/base.html" %}

{% block head_title %}- shopping cart{% endblock %}

{% block title %}
    Shopping cart
{% endblock %}

{% block content %}
    {% if items %}
        {% for item in items %}
            <p>
                <img src="{{ item.product.image }}">
                <a href="{% url 'product' item.product.id %}">{{ item.product.name }}</a>
                {{ item.product.price }}
                {{ item.count }}
                {{ item.sum }}
                <form action="{% url 'del_from_cart' %}" method="post">
                    {% csrf_token %}
                    <input name="product" type="hidden" value="{{ item.product.id }}">
                    <input type="submit" value="Remove from cart">
                </form>
            </p>
        {% endfor %}
            <p>{{ page }}</p>
    {% else %}
        <p>There is no products</p>
    {% endif %}
    <p>Sum: {{ sum }}</p>
{% endblock %}

Shop/templates/shop_app/categories.html
{% extends "shop_app/base.html" %}
{% load tags %}
{% block head_title %}- categories{% endblock %}

{% block title %}
    Categories
{% endblock %}

{% block content %}
    <ul>
    {% for c in category_list %}
        <li><a href="{% url 'category_prods' c.id %}">{{ c.name }}</a>
        {% children_tag c %}
        </li>
    {% endfor %}
    </ul>
{% endblock %}

Shop/templates/shop_app/children.html
{% load tags %}

<ul>
    {% for child in children %}
        <li> <a href="{% url 'category_prods' child.id %}">{{ child.name }}</a></li>
            {% if child.children.count > 0 %}
            {% children_tag child %}
            {% endif %}
    {% endfor %}
</ul>

Shop/templates/shop_app/edit_profile.html
{% extends "shop_app/base.html" %}
{% load static %}

{% block head_title %}- edit profile{{ profile.user }}{% endblock %}

{% block title %}
    {{ profile.user }}
{% endblock %}

{% block content %}
    <form action="{% url 'edit_profile' %}" method="POST" enctype="multipart/form-data" >
        {% csrf_token %}
        {% if image %}
        <p><img src="{{ image.url }}"></p>
        {% else %}
        <img src="/media/avatars/no_avatar.jpg" width="200"/>
        {% endif %}
        {{ form.as_p }}
        <input type="submit" value="send" />
    </form>
{% endblock %}

Shop/templates/shop_app/index.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

</body>
</html>

Shop/templates/shop_app/my_orders.html
{% extends "shop_app/base.html" %}

{% block head_title %}- order list{% endblock %}

{% block title %}
    My orders
{% endblock %}

{% block content %}
    {% if order_list %}
        {% for order in order_list %}
            <div class="list_item">
            {% if order.product.image %}
                <img src="{{ order.product.image.url }}"/>
            {% endif %}
                <a href="{% url 'product' order.product.id %}">{{ order.product.name }}</a>
                {{ order.product.price }}
                {{ order.count }}
                {{ order.status }}
            </div>
        {% endfor %}
            <p>{{ page }}</p>
    {% else %}
        <p>There is no orders</p>
    {% endif %}
{% endblock %}

Shop/templates/shop_app/product.html
{% extends "shop_app/base.html" %}

{% block head_title %}- {{ product.name }}{% endblock %}

{% block title %}
    {{ product.name }}
{% endblock %}

{% block content %}
    <ol class="breadcrumb">
        {% for cat in category_chain %}
            <li><a href="{% url 'category_prods' cat.id %}">{{ cat.name }}</a></li>
        {% endfor %}
    </ol>
    <p>Category: {{ product.category.name }}</p>
    <p><img src="{{ product.image }}"/></p>
    <p>Price: {{ product.price }}</p>
    <p>Description: {{ product.description }}</p>
    <p><form action="{% url 'add_to_cart' %}" method="post">
        {% csrf_token %}
        <p>Count: <input name="count" type="number" value="1"></p>
        <input name="product" type="hidden" value="{{ product.id }}">
        <p><input type="submit" value="Add to shopping cart"></p>
    </form></p>
{% endblock %}

Shop/templates/shop_app/product_list.html
{% extends "shop_app/base.html" %}
{% load tags %}

{% block head_title %}- product list{% endblock %}

{% block title %}
    Products
{% endblock %}

{% block sub_title %}
    {% if query %}
        Results for query: "{{ query }}"
    {% endif %}
    {% if category %}
        Results for category: "{{ category }}"
    {% endif %}
{% endblock %}

{% block content %}
    {% if product_list %}
        {% for product in product_list %}
            <div class="list_item">
                {% if product.image %}
                <img src="{{ product.image.url }}"/>
                {% endif %}
                <a href="{% url 'product' product.id %}">{{ product.name }}</a> {{ product.price }}
            </div>
        {% endfor %}
        {% if is_paginated %}
            <div class="pagination">
                <span class="page-links">
                    {% if page_obj.has_previous %}
                        <a href="?{% url_replace request 'page' page_obj.previous_page_number %}">previous</a>
                    {% endif %}
                    <span class="page-current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>
                    {% if page_obj.has_next %}
                        <a href="?{% url_replace request 'page' page_obj.next_page_number %}">next</a>
                    {% endif %}
                </span>
            </div>
        {% endif %}
    {% else %}
        <p>There is no products</p>
    {% endif %}
        <form action="{% url 'search' %}" method="get">
            <p>
                <label for="amount">Price range:</label>
                <input type="text" id="amount" readonly style="border:0; color:#f6931f; font-weight:bold;">
                <input id="min_val" type="hidden" name="min" value="{% if request.GET.min %}{{ request.GET.min }}{% else %}0{% endif %}">
                <input id="max_val" type="hidden" name="max" value="{% if request.GET.max %}{{ request.GET.max }}{% else %}5000000{% endif %}">
                {% if category %}
                <input type="hidden" name="category" value="{{ category.id }}">
                {% elif request.GET.category %}
                <input type="hidden" name="category" value="{{ request.GET.category }}">
                {% endif %}
                <input type="submit" value="filter">
            </p>
            <div id="slider-range" style="width:1000px"></div>
        </form>
        <script>
            $(function() {
                $( "#slider-range" ).slider({
                    range: true,
                    min: 0,
                    max: 5000000,
                    values: [ {% if request.GET.min %}{{ request.GET.min }}{% else %}0{% endif %}, {% if request.GET.max %}{{ request.GET.max }}{% else %}5000000{% endif %} ],
                    step: 50,
                    slide: function( event, ui ) {
                        $( "#amount" ).val(ui.values[ 0 ] + " RUB - " + ui.values[ 1 ] + " RUB");
                        $("#min_val").val(ui.values[ 0 ]);
                        $("#max_val").val(ui.values[ 1 ]);
                    }
                });
                $( "#amount" ).val($( "#slider-range" ).slider( "values", 0 ) + " RUB" +
                " - " + $( "#slider-range" ).slider( "values", 1 ) + " RUB" );
                $("#min_val").val($( "#slider-range" ).slider( "values", 0 ));
                $("#max_val").val($( "#slider-range" ).slider( "values", 1 ));
            });
         </script>
{% endblock %}

Shop/templates/shop_app/sign_up.html
{% load static %}
<!DOCTYPE html>
<html>
    <head lang="en">
        <meta charset="UTF-8">
        <title>Shop - Sign Up</title>
        <link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
    </head>
    <body>
        <h1>Sign up</h1>

        <form action="{% url 'sign_up' %}" method="POST">

            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="sign in"/>
        </form>
    </body>
</html>